Add git actions

diff --git a/.github/workflows/build-android.yml b/.github/workflows/build-android.yml
--- a/.github/workflows/build-android.yml
+++ b/.github/workflows/build-android.yml
@@ -1,21 +1,22 @@
 name: Build Android APK
+
 on:
-  pull_request:
+  push:
     branches:
       - dev
       - staging
       - production
-    paths:
-      - "**/*"
   workflow_dispatch:
     inputs:
       build-type:
-        description: "Build Type (all/v8/v7/arm64/x86)"
+        description: "Build Type (stg/prd)"
         required: false
-        default: "all"
+        default: "stg"
+
 jobs:
   build-android:
     runs-on: ubuntu-latest
+
     steps:
       # Checkout the repository code
       - uses: actions/checkout@v4
@@ -27,42 +28,15 @@ jobs:
           distribution: "temurin"
           java-version: "17"
 
-      # Set up Node.js 21
+      # Set up Node.js
       - name: Set up Node.js
         uses: actions/setup-node@v4
         with:
           node-version: "21"
 
-      # Cache node modules
-      # - name: Cache node modules
-      #   uses: actions/cache@v4
-      #   with:
-      #     path: ~/.npm
-      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
-      #     restore-keys: |
-      #       ${{ runner.os }}-node-
-
-      # Install project dependencies
       - name: Install Dependencies
         run: npm install
 
-      # Prebuild for Android
-      # - name: Prebuild for Android
-      #   run: npx expo prebuild --clean --platform android
-
-      # Create and Push New Branch for Android Folder
-      # - name: Push Android Folder to New Branch
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #   run: |
-      #     git config --global user.name 'github-actions'
-      #     git config --global user.email 'github-actions@github.com'
-      #     git checkout -b update-android-folder/${{ github.run_id }}
-      #     git add android
-      #     git commit -m "Update Android project files" || echo "No changes to commit"
-      #     git push origin update-android-folder/${{ github.run_id }}
-
-      # Make gradlew executable
       - name: Make gradlew executable
         run: chmod +x android/gradlew
 
@@ -71,15 +45,30 @@ jobs:
         working-directory: android
         run: ./gradlew clean
 
-      # Build Release APK
-      - name: Build Release APK
+      # Determine Build Type
+      - name: Determine Build Type
+        id: build_type
+        run: |
+          if [[ "${{ github.ref_name }}" == "staging" || "${{ github.ref_name }}" == "dev" ]]; then
+            echo "BUILD_TYPE=assembleStaging" >> $GITHUB_ENV
+          elif [[ "${{ github.ref_name }}" == "production" ]]; then
+            echo "BUILD_TYPE=assembleRelease" >> $GITHUB_ENV
+          else
+            echo "Invalid branch for APK build."
+            exit 1
+          fi
+
+      # Build APK
+      - name: Build APK
         working-directory: android
-        run: ./gradlew assembleRelease
+        run: ./gradlew $BUILD_TYPE
 
       # Upload APK as artifact
       - name: Upload APK
         uses: actions/upload-artifact@v4
         with:
-          name: app-release
-          path: android/app/build/outputs/apk/release/*.apk
+          name: ${{ github.ref_name }}-apk
+          path: |
+            android/app/build/outputs/apk/staging/*.apk
+            android/app/build/outputs/apk/release/*.apk
           retention-days: 5
